// src/components/layouts/Header.tsx
import React, { useContext, useMemo } from 'react'
import Avatar from '../common/Avatar'
import classNames from 'classnames'
import { Link } from 'gatsby'
import { HEADER_HEIGHT } from '@/const'
import ThemeContext from '@/context/theme'

const HeaderNavi: React.FC = () => {
  const { color, toggleTheme } = useContext(ThemeContext)
  const classes = useMemo(() => {
    return {
      wrapper: classNames(
        'hidden lg:block children:inline-block text-gray-500 space-x-5 ml-10 text-sm'
      ),
      item: classNames(
        'transition-colors duration-300 hover:text-white',
        'cursor-pointer'
      )
    }
  }, [])

  const handleToggleTheme = () => {
    if (color === 'dark') {
      toggleTheme('light')
    } else {
      toggleTheme('dark')
    }
  }

  return (
    <nav className={classes.wrapper}>
      <Link to="/" activeClassName="text-white" className={classes.item}>
        Home
      </Link>
      <a
        target="_blank"
        href="https://github.com/n2ptune/imkh.dev"
        className={classes.item}
      >
        Github
      </a>
      <span className={classes.item}>Search</span>
      <span onClick={handleToggleTheme} className={classes.item}>
        {color === 'dark' ? 'Light Mode' : 'Dark Mode'}
      </span>
    </nav>
  )
}

export default function Header({ children }: React.PropsWithChildren<unknown>) {
  return (
    <header
      className={`flex flex-row fixed top-0 left-0 w-full items-center flex-nowrap px-2 lg:px-6 bg-black-primary-300 z-50 text-white ${HEADER_HEIGHT.class} border-b border-black-primary-100`}
    >
      <div className="flex items-center flex-nowrap space-x-2">
        <Avatar />
        <h1 className="text-xl font-semibold">imkh.dev</h1>
      </div>
      <HeaderNavi />
    </header>
  )
}

// src/components/layouts/main/Header.vue
<template>
  <header>
    <div class="flex items-center w-full">
      <Avatar class="shadow-2xl object-cover mr-0 lg:mr-2" width="40px" />
      <ul class="text-base">
        <li class="menu-link">
          <g-link to="/">
            Home
          </g-link>
        </li>
        <li class="menu-link">
          <a href="https://portfolio.imkh.dev/" target="_blank">
            Portfolio
          </a>
        </li>
        <li class="menu-link">
          <a href="http://github.com/n2ptune" target="_blank">
            Github
          </a>
        </li>
      </ul>
      <div class="ml-auto">
        <font-awesome
          :icon="['fas', 'search']"
          class="font-normal cursor-pointer transition-colors duration-300 text-white-500 hover:text-white-f"
          size="lg"
          @click="handleSearchForm"
        />
      </div>
      <Overlay
        :handler="isSearchOverlay"
        :style="{ overflow: 'auto' }"
        :z-index="1"
        distance="72px"
        key="search"
        @click-outside="clickOutsideSearchOverlay"
      >
        <SearchForm @close-form="closeForm" />
      </Overlay>
    </div>
  </header>
</template>

<script>
import Avatar from '@/components/utils/Avatar.vue'
import SearchForm from '@/components/search/Form.vue'

export default {
  components: {
    Avatar,
    SearchForm
  },

  data: () => ({
    isSearchOverlay: false
  }),

  methods: {
    clickOutsideSearchOverlay() {
      this.isSearchOverlay = !this.isSearchOverlay
    },
    closeForm() {
      this.isSearchOverlay = false
    },
    handleSearchForm() {
      this.isSearchOverlay = !this.isSearchOverlay
    }
  }
}
</script>

<style lang="postcss" scoped>
header {
  @apply flex justify-between items-center px-2 py-4 bg-dark-lighten
  fixed w-full z-50 top-0;

  @screen md {
    @apply px-4;
  }

  & .menu-link {
    @apply inline-block ml-4 text-white-300 transition-colors duration-300;

    & .active--exact,
    &:hover {
      @apply text-white-700;
    }
  }
}
</style>
