// src/components/layouts/main/PostCard.vue
<template>
  <div class="post">
    <div class="mb-1">
      <g-link :to="post.path">
        <g-image
          v-if="post.cover_image"
          :src="post.cover_image"
          cover
          blur="4"
          class="rounded-none md:rounded-t-lg"
        />
      </g-link>
    </div>
    <g-link :to="post.path">
      <div class="pb-16">
        <div class="p-4">
          <div class="text-2xl font-bold title">
            {{ post.title }}
          </div>
          <div class="text-base text-white-400 mt-5 desc">
            {{ post.cover_image ? post.description : post.excerpt + '...' }}
          </div>
          <tag-list :tag="post.tags" />
        </div>
      </div>
    </g-link>
    <div
      class="absolute bottom-0 left-0 h-12 w-full border-t border-elevation-300"
    >
      <div class="bottom-left space-x-3">
        <font-awesome :icon="['fas', 'bookmark']" class="inline-block" />
        <p class="inline-block">{{ post.date }}</p>
      </div>
      <div class="bottom-right">
        읽는 데 {{ post.timeToRead }}분 걸림
        <span class="text-white-f">{{ toReadLevel(post.timeToRead) }} </span>
      </div>
    </div>
  </div>
</template>

<script>
import TimeReadMixins from '@/components/mixins/TimeReadMixins'
import TagList from '@/components/tag/List.vue'

export default {
  components: {
    TagList
  },

  props: {
    post: {
      type: Object,
      required: true
    }
  },

  mixins: [TimeReadMixins]
}
</script>

<style lang="postcss" scoped>
.post {
  @apply my-3 bg-elevation-200 transition-all duration-300
  relative;

  flex: 0 1 450px;

  &:hover {
    @apply transform -translate-y-1;

    & .title {
      @apply text-white-f;
    }

    & .desc {
      @apply text-white-600;
    }
  }

  & .bottom-right {
    right: 15px;
  }

  & .bottom-left {
    left: 15px;
  }

  & .bottom-left,
  & .bottom-right {
    @apply absolute text-sm text-white-500;

    top: 25%;
  }

  & .title,
  & .desc {
    @apply transition-colors duration-300;
  }

  & .title {
    @apply text-white-700;
  }
}

@screen md {
  .post {
    @apply m-4 rounded-lg;
  }
}
</style>

// src/components/main/PostCard.tsx
import { useRelativeDate } from '@/hooks/date'
import { useTimeToReadToText } from '@/hooks/posts'
import classNames from 'classnames'
import { getImage, GatsbyImage } from 'gatsby-plugin-image'
import React from 'react'
import { BsBookmarkFill } from 'react-icons/bs'
import TagList from './TagList'
import { Link } from 'gatsby'

type PostCardProps = {
  post: any
}

const CARD_HEIGHT = '400px'
const CARD_IMAGE_HEIGHT = '150px'

const PostCard: React.FC<PostCardProps> = ({ post }) => {
  const coverImage = getImage(post.frontmatter.cover_image)
  const date = useRelativeDate(post.frontmatter.date as string)
  const ttr = useTimeToReadToText(post.timeToRead)

  const classes = {
    wrapper: classNames(
      'col-span-12 md:col-span-6 lg:col-span-4 cursor-pointer',
      'transition-transform duration-200 transform',
      'hover:-translate-y-2 group'
    ),
    image: classNames('rounded bg-gray-200 dark:bg-black-primary-300 w-full'),
    body: classNames(
      'bg-white dark:bg-black-primary-100 shadow-lg rounded',
      'h-full relative'
    ),
    content: classNames('p-6 lg:p-4 space-y-2'),
    groupText: classNames(
      'text-gray-400 dark:text-white dark:text-opacity-40 group-hover:text-black-primary-500 dark:group-hover:text-white dark:group-hover:text-opacity-100 transition-colors duration-300'
    )
  }

  return (
    <Link className={classes.wrapper} to={post.fields.slug}>
      <div style={{ height: CARD_HEIGHT }}>
        <div className={classes.body}>
          {coverImage ? (
            <GatsbyImage
              className={classes.image}
              image={coverImage}
              alt="image"
              style={{ height: CARD_IMAGE_HEIGHT }}
            />
          ) : null}
          <div className={classes.content}>
            <div className="text-lg font-bold">{post.frontmatter.title}</div>
            <div className={classes.groupText}>{post.excerpt}</div>
          </div>
          <TagList tags={post.frontmatter.tags} />
          <div className="flex items-center justify-between w-full absolute bottom-0 p-4 border-t border-gray-200 dark:border-black-primary-50">
            <span className={classes.groupText + ' text-sm'}>
              <BsBookmarkFill className="inline-block mr-2" />
              <span>{date}</span>
            </span>
            <span className="text-sm">{ttr}</span>
          </div>
        </div>
      </div>
    </Link>
  )
}

export default PostCard
