// src/components/layouts/Header.tsx
import React, { useMemo } from 'react'
import Avatar from '../common/Avatar'
import classNames from 'classnames'
import { Link } from 'gatsby'
import { HEADER_HEIGHT } from '@/const'

const HeaderNavi: React.FC = () => {
  const classes = useMemo(() => {
    return {
      wrapper: classNames(
        'hidden lg:block children:inline-block text-gray-500 space-x-5 ml-10'
      ),
      item: classNames(
        'transition-colors duration-300 hover:text-white text-sm'
      )
    }
  }, [])

  return (
    <nav className={classes.wrapper}>
      <Link to="/" activeClassName="text-white" className={classes.item}>
        Home
      </Link>
      <a
        target="_blank"
        href="https://github.com/n2ptune/imkh.dev"
        className={classes.item}
      >
        Github
      </a>
    </nav>
  )
}

export default function Header({ children }: React.PropsWithChildren<unknown>) {
  return (
    <header
      className={`flex flex-row fixed top-0 left-0 w-full items-center flex-nowrap px-2 lg:px-6 bg-black-primary-300 z-50 text-white ${HEADER_HEIGHT.class} border-b border-black-primary-100`}
    >
      <div className="flex items-center flex-nowrap space-x-2">
        <Avatar />
        <h1 className="text-xl font-semibold">imkh.dev</h1>
      </div>
      <HeaderNavi />
    </header>
  )
}

// components/common/Header.vue
<script lang="ts" setup></script>

<template>
  <header
    class="sticky top-0 z-50 p-4 border-b h-[72px] dark:border-neutral-900 dark:bg-dark"
  >
    <div class="mx-auto h-full">
      <div class="flex justify-between items-center h-full">
        <div class="text-base lg:text-lg xl:text-x">
          <span>DEVLOG</span>
          <span class="text-gray-300 dark:text-gray-500 mx-2">|</span>
          <span>개발 블로그</span>
        </div>
        <div>
          <a href="https://github.com/n2ptune" target="_blank" class="group">
            <Icon
              name="uil:github"
              size="36"
              class="transition duration-300 text-black opacity-80 dark:text-white group-hover:opacity-100"
            />
          </a>
        </div>
      </div>
    </div>
  </header>
</template>
