// src/components/layouts/Header.tsx
import React from 'react'
import Avatar from '../common/Avatar'

export default function Header({ children }: React.PropsWithChildren<unknown>) {
  return (
    <header className="h-16 flex flex-row items-center flex-nowrap px-2 lg:px-6 justify-between">
      <div className="flex items-center flex-nowrap space-x-2">
        <Avatar />
        <h1 className="text-2xl font-semibold">imkh.dev</h1>
      </div>
    </header>
  )
}

// src/components/Header.vue
<template>
  <div
    class="font-head header flex items-center justify-center flex flex-col py-12"
  >
    <div class="text-white-f text-3xl">
      {{ $static.metadata.siteName }}
    </div>
    <div class="text-white-700 text-lg">
      {{ $static.metadata.siteDescription }}
    </div>
  </div>
</template>

<static-query>
query {
  metadata {
    siteName
    siteDescription
  }
}
</static-query>

.<style lang="postcss" scoped></style>
